<a href="https://colab.research.google.com/github/siddh-webd-ml/Machine-Learning/blob/main/dmnumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Different ways of creating Numpy Arrays**

In [ ]:
import numpy as np

In [ ]:
var_1=np.array([1,2,3,4])

In [ ]:

print(var_1)

[1 2 3 4]


In [ ]:
var_2=np.array([[1,2,3],[4,5,6]])

In [ ]:
print(var_2)

[[1 2 3]
 [4 5 6]]


In [ ]:
# array of zeros
z=np.zeros((3,3),dtype="int")
z

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
# array of ones

x=np.ones((4,4),dtype="int")
x

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
# array of random elements:
np.random.seed(4) #it help to fix the randomness
random=np.random.rand(4,4)
random

array([[0.96702984, 0.54723225, 0.97268436, 0.71481599],
       [0.69772882, 0.2160895 , 0.97627445, 0.00623026],
       [0.25298236, 0.43479153, 0.77938292, 0.19768507],
       [0.86299324, 0.98340068, 0.16384224, 0.59733394]])

In [ ]:
np.random.seed(4)
np.random.randn(4,4)

array([[ 0.05056171,  0.49995133, -0.99590893,  0.69359851],
       [-0.41830152, -1.58457724, -0.64770677,  0.59857517],
       [ 0.33225003, -1.14747663,  0.61866969, -0.08798693],
       [ 0.4250724 ,  0.33225315, -1.15681626,  0.35099715]])

In [ ]:
np.random.seed(4)
x_1=np.random.randint(low=50,high=100,size=(4,4))

# **Slicing and Indexing**

In [ ]:
x_1

array([[54, 94, 82, 52],
       [99, 95, 52, 71],
       [70, 64, 60, 50],
       [67, 60, 53, 83]])

In [ ]:
x_1[1,1]

58

In [ ]:
x_1[3,0]

94

In [ ]:
x_1[0:2,0:2]

array([[54, 94],
       [99, 95]])

In [ ]:
x_1[2:3,2:]

array([[60, 50]])

In [ ]:

np.identity(3,dtype="int")

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
b=np.arange(1,13).reshape(3,4)

In [ ]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b=b.ravel()


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
c=np.arange(1,13).reshape(4,3)
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
c.transpose()

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [ ]:
mat_1=np.arange(12).reshape(3,4)
mat_2=np.arange(12,24).reshape(3,4)


In [ ]:
mat_1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
mat_2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
v=np.vstack((mat_1,mat_2))
v

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
h=np.hstack((mat_1,mat_2))
h

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
np.hsplit(v,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16],
        [20]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13],
        [17],
        [21]]),
 array([[ 2],
        [ 6],
        [10],
        [14],
        [18],
        [22]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19],
        [23]])]

In [ ]:
np.vsplit(h,3)

[array([[ 0,  1,  2,  3, 12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7, 16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11, 20, 21, 22, 23]])]