<a href="https://colab.research.google.com/github/siddh-webd-ml/Machine-Learning/blob/main/NUmpyBASICS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

array_1 = np.array([1,2,3])
print(array_1)
array_2=np.array((30,40,50))
print(array_2)

array_3 = np.array([[1,2,3],[4,5,6],[4,5,6]])
print(array_3)

np.array([1,2,3,4],dtype="complex")
np.array([1,2,3,4],dtype="float")
list_1=[10,20,30,40]
print(list_1)

#What is the major diff between numpy array and python lists

array_1
array_2


print(array_1+array_2)

list_1=[1,2,3]
list_2=[30,40,50]

print(list_1+list_2)

list_ans=[]
for i,j in zip(list_1,list_2):
  list_ans.append(i+j)
print(list_ans)

array_1.ndim

array_3.shape

array_1.size

a1=np.arange(10)
print(a1)


a2=np.arange(10,dtype=float).reshape(5,2)
print(a2)

a3=np.arange(12,dtype=float).reshape(4,3)
print(a3)

a3.astype(np.int64)

for i in a2:
  print(i)

for i in np.nditer(a2):
  print(i)

print(a2>5)

[1 2 3]
[30 40 50]
[[1 2 3]
 [4 5 6]
 [4 5 6]]
[10, 20, 30, 40]
[31 42 53]
[1, 2, 3, 30, 40, 50]
[31, 42, 53]
[0 1 2 3 4 5 6 7 8 9]
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
[0. 1.]
[2. 3.]
[4. 5.]
[6. 7.]
[8. 9.]
0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
[[False False]
 [False False]
 [False False]
 [ True  True]
 [ True  True]]
